{% set name = "jsonargparse" %}
{% set version = "4.7.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jsonargparse-{{ version }}.tar.gz
  sha256: 208c85bfc3f3c32b4553583cf86f734193b760ca24d44b5ca09b52d8693ea815

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install .[all] -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5
    - pyyaml >=3.13

test:
  imports:
    - jsonargparse
    - jsonargparse_tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/omni-us/jsonargparse
  summary: Parsing of command line options, yaml/jsonnet config files and/or environment variables based on argparse.
  license: MIT
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - olegtarasov
