{% set name = "jsonargparse" %}
{% set version = "4.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jsonargparse-{{ version }}.tar.gz
  sha256: 351b49b4c734034c5b5128109802fc94b3cddcd6e9bdbfec1123d285958ce490

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install .[all] -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5
    - pyyaml >=3.13

test:
  imports:
    - jsonargparse
    - jsonargparse_tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/omni-us/jsonargparse
  summary: Parsing of command line options, yaml/jsonnet config files and/or environment variables based on argparse.
  license: MIT
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - olegtarasov
